In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt  
import seaborn as sns
%matplotlib inline 

In [2]:
train=pd.read_csv(r"D:\Master Program\Machine Learning\Projects\Projects\Machine-Learning--Projects-master\Projects\Projects for Submission\Project 1 - Mercedes-Benz Greener Manufacturing\Dataset for the project\train.csv" )
test=pd.read_csv(r"D:\Master Program\Machine Learning\Projects\Projects\Machine-Learning--Projects-master\Projects\Projects for Submission\Project 1 - Mercedes-Benz Greener Manufacturing\Dataset for the project\test.csv" )

In [3]:
print(train.shape)
print(test.shape)

(4209, 378)
(4209, 377)


In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [5]:
train.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

# Check for null and unique values for test and train sets and specifing the columns with zero variance and the columns with categorical data.

In [6]:
for x in train.isnull().any():
    if x==True:
        print(1)

In [7]:
for x in test.isnull().any():
    if x==True:
        print(1)

In [8]:
remove=[]
for col in train.columns:
    if train[col].dtype!="O":
         if train[col].std()==0:
                 remove.append(col)
                    
print(remove)

['X11', 'X93', 'X107', 'X233', 'X235', 'X268', 'X289', 'X290', 'X293', 'X297', 'X330', 'X347']


In [9]:
objest=[]
for col in train.columns:
    if train[col].dtype=="O":
             objest.append(col)
                    
print(objest)

['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8']


In [10]:
for col in objest:
    print(col)
    print(train[col].unique())
    print("------------------------------------------------------------------------")

X0
['k' 'az' 't' 'al' 'o' 'w' 'j' 'h' 's' 'n' 'ay' 'f' 'x' 'y' 'aj' 'ak' 'am'
 'z' 'q' 'at' 'ap' 'v' 'af' 'a' 'e' 'ai' 'd' 'aq' 'c' 'aa' 'ba' 'as' 'i'
 'r' 'b' 'ax' 'bc' 'u' 'ad' 'au' 'm' 'l' 'aw' 'ao' 'ac' 'g' 'ab']
------------------------------------------------------------------------
X1
['v' 't' 'w' 'b' 'r' 'l' 's' 'aa' 'c' 'a' 'e' 'h' 'z' 'j' 'o' 'u' 'p' 'n'
 'i' 'y' 'd' 'f' 'm' 'k' 'g' 'q' 'ab']
------------------------------------------------------------------------
X2
['at' 'av' 'n' 'e' 'as' 'aq' 'r' 'ai' 'ak' 'm' 'a' 'k' 'ae' 's' 'f' 'd'
 'ag' 'ay' 'ac' 'ap' 'g' 'i' 'aw' 'y' 'b' 'ao' 'al' 'h' 'x' 'au' 't' 'an'
 'z' 'ah' 'p' 'am' 'j' 'q' 'af' 'l' 'aa' 'c' 'o' 'ar']
------------------------------------------------------------------------
X3
['a' 'e' 'c' 'f' 'd' 'b' 'g']
------------------------------------------------------------------------
X4
['d' 'b' 'c' 'a']
------------------------------------------------------------------------
X5
['u' 'y' 'x' 'h' 'g' 'f' 'j' 'i' 'd' 'c' 

In [11]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
pca=PCA()
sc=StandardScaler()
le=LabelEncoder()

# removing columns with zero variance.

In [12]:
train_re=train.drop(remove, axis =1)
test_re=test.drop(remove, axis =1)

In [13]:
train_re.shape

(4209, 366)

# Apply label encoder.

In [14]:
for col in objest :
    train_re[col]=le.fit_transform(train_re[col])
for col in objest :
    test_re[col]=le.fit_transform(test_re[col])

# Perform dimensionality reduction.

In [15]:
feature=train_re.drop("y", axis=1)
target=train_re["y"]

In [16]:
sc.fit_transform(feature)

array([[-1.72565045,  0.16301209,  1.39348787, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [-1.72318873,  0.16301209,  1.15902093, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [-1.72277844, -0.71055977,  1.51072134, ..., -0.04081511,
        -0.02180363, -0.03778296],
       ...,
       [ 1.72568262, -1.58413164,  1.39348787, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [ 1.72691348, -1.51133398,  0.924554  , ..., -0.04081511,
        -0.02180363, -0.03778296],
       [ 1.72773405,  1.18217927,  0.924554  , ..., -0.04081511,
        -0.02180363, -0.03778296]])

In [17]:
sc.transform(test_re)

array([[-1.72524016, -0.63776212,  1.39348787, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [-1.72482987,  0.89098865, -0.95118151, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [-1.72441959, -0.63776212,  1.39348787, ..., -0.04081511,
        -0.02180363, -0.03778296],
       ...,
       [ 1.7260929 ,  1.25497692,  1.39348787, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [ 1.72650319, -1.65692929,  1.39348787, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [ 1.72732376,  0.89098865, -1.18564845, ..., -0.04081511,
        -0.02180363, -0.03778296]])

In [18]:
Pfeature=pca.fit_transform(feature)

In [19]:
var=pca.explained_variance_ratio_.cumsum()

In [20]:
var

array([0.99991541, 0.99994973, 0.99996887, 0.99997981, 0.99998806,
       0.99999465, 0.99999607, 0.99999674, 0.99999713, 0.99999739,
       0.9999976 , 0.99999782, 0.999998  , 0.99999815, 0.99999828,
       0.9999984 , 0.99999849, 0.99999857, 0.99999865, 0.99999872,
       0.99999879, 0.99999885, 0.9999989 , 0.99999895, 0.999999  ,
       0.99999904, 0.99999908, 0.99999912, 0.99999915, 0.99999919,
       0.99999922, 0.99999925, 0.99999927, 0.9999993 , 0.99999933,
       0.99999935, 0.99999937, 0.99999939, 0.99999941, 0.99999943,
       0.99999945, 0.99999946, 0.99999948, 0.9999995 , 0.99999951,
       0.99999953, 0.99999954, 0.99999955, 0.99999957, 0.99999958,
       0.99999959, 0.9999996 , 0.99999962, 0.99999963, 0.99999964,
       0.99999965, 0.99999966, 0.99999967, 0.99999968, 0.99999969,
       0.99999969, 0.9999997 , 0.99999971, 0.99999972, 0.99999973,
       0.99999973, 0.99999974, 0.99999975, 0.99999975, 0.99999976,
       0.99999977, 0.99999977, 0.99999978, 0.99999978, 0.99999

In [21]:
pca1=PCA(n_components=1)

In [22]:
Ffeature=pca1.fit_transform(feature)
Ftest=pca1.transform(test_re)

In [23]:
pca1.explained_variance_ratio_

array([0.99991541])

In [24]:
print(Ffeature.shape)
print(Ftest.shape)
print(target.shape)

(4209, 1)
(4209, 1)
(4209,)


#### now our data is so prepared and let's move on 

# Predict your test_df values using XGBoost.

In [25]:
from xgboost import XGBRegressor
model1=XGBRegressor(alpha=1)

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(Ffeature, target, test_size=0.25, random_state=10)

In [27]:
model1.fit(x_train,y_train)

XGBRegressor(alpha=1, base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=8,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=1,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [28]:
y_pred1=model1.predict(x_test)

from sklearn.metrics import mean_squared_error, mean_absolute_error
from math import sqrt

rmse1=sqrt(mean_squared_error(y_pred1,y_test))
mae1=mean_absolute_error(y_pred1,y_test)

print(rmse1,"\n ", mae1)

13.813281198530323 
  10.908888142324015


In [29]:
Prediction=model1.predict(Ftest)

In [30]:
Prediction

array([127.34081 , 127.34081 , 127.34081 , ..., 106.515205,  93.52943 ,
        93.52943 ], dtype=float32)

### let's try KFold and cross_val_score

In [31]:
from xgboost import XGBRegressor
model2=XGBRegressor(alpha=1)

from sklearn.model_selection import KFold, cross_val_score
kfold=KFold(n_splits=10,  shuffle=True)

In [32]:
results =cross_val_score(model2,Ffeature,target, cv=kfold)
print(results)

[-0.22636611 -0.21300683 -0.14468613 -0.20108725 -0.16293003 -0.07077797
 -0.16306149 -0.19100773 -0.17244427 -0.22753402]


In [33]:
ave_err=results.mean()
ave_err

-0.1772901821166305

In [34]:
model2.fit(Ffeature,target)

XGBRegressor(alpha=1, base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=100, n_jobs=8,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=1,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [35]:
prediction_model2=model2.predict(Ftest)

In [36]:
prediction_model2

array([127.58402 , 127.58402 , 127.58402 , ..., 106.4776  ,  93.466805,
        93.466805], dtype=float32)

### let's see if we predicted y_test by our new model and measure the RMSE & MAE for the second model and compare with the first one

In [37]:
y_pred2=model2.predict(x_test)

In [38]:
rmse2=sqrt(mean_squared_error(y_pred2,y_test))
mae2=mean_absolute_error(y_pred2,y_test)

print(rmse2,"\n ", mae2)

10.008262137840877 
  8.028446965086268


In [39]:
RMSE_Ratio_2_1=rmse2/rmse1
MAE_Ratio_2_1=mae2/mae1
print("The Ratio between the RMSE from the second model to the first one is :")
print(RMSE_Ratio_2_1)
print("The Ratio between the MAE from the second model to the first one is :")
print(MAE_Ratio_2_1)

The Ratio between the RMSE from the second model to the first one is :
0.7245390862603822
The Ratio between the MAE from the second model to the first one is :
0.735954650954547


### as you can see here the ratio of the error in model2 to model1 is smaller than 1 by more than 0.25 and this implies that model2 is better than model1 and this implies that using KFold and cross_val_score instead of using train_test_split in model selection leads to more accurate results.  